# Generated by Django 5.0.3 on 2024-08-09 17:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=10)),
                ('check_in', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PND', 'Pending'), ('INP', 'In Progress'), ('COM', 'Complete'), ('BIL', 'Billed')], max_length=150)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('additional_parts', models.ManyToManyField(blank=True, null=True, to='Inventory.spareparts')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.customer')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employeeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('invoice_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('vehicle_out', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField()),
                ('tax', models.FloatField()),
                ('gross_total', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.order')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTypes',
            fields=[
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=255)),
                ('service_etc', models.CharField(max_length=255)),
                ('service_cost', models.FloatField()),
                ('spare_parts', models.ManyToManyField(to='Inventory.spareparts')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('manufacture_year', models.DateField()),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.vehiclemodel')),
                ('service_types', models.ManyToManyField(to='Management.servicetypes')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='vehicle_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.vehicleservice'),
        ),
    ]
