# Generated by Django 5.0.3 on 2024-05-30 03:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='static/media/vehicle_models')),
                ('log', models.FileField(upload_to='static/media/logs')),
            ],
        ),
        migrations.CreateModel(
            name='SpareParts',
            fields=[
                ('part_no', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('cost', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.vehiclemodel')),
            ],
        ),
    ]
